import { SpinalNode, SpinalContext } from 'spinal-env-viewer-graph-service';
import { ISubscribeOptions } from '../interfaces';
import SocketHandler from "../socket/socketHandlers";
declare class SpinalGraphUtils {
    spinalConnection: spinal.FileSystem;
    private nodeBinded;
    private static instance;
    private socketHandler;
    private constructor();
    static getInstance(): SpinalGraphUtils;
    init(socketHandler: SocketHandler): Promise<void>;
    bindNode(node: SpinalNode<any>, context: SpinalContext<any>, options: ISubscribeOptions, eventName?: string): Promise<void>;
    bindContextTree(startNode: SpinalNode<any>, context: SpinalContext<any>): void;
    bindChildNotInContext(node: SpinalNode<any>): Promise<void>;
    rebindAllNodes(): Promise<void>;
    private _rebindNode;
    private _unbindAllNodes;
    private _unbindNode;
    private _unbindBindProcess;
    private _bindAllChild;
    private _bindChildInContext;
    private _getRelationNameNotInContext;
    private _getRelationNames;
    private _bindInfoAndElement;
    private _addNodeToBindedNode;
    private _listenAddChildEvent;
    private _listenAddChildInContextEvent;
    private _listenRemoveChildEvent;
    private _listenAddChildrenEvent;
    private _activeEventSender;
    private _findNode;
    private _callbackListen;
}
export declare const spinalGraphUtils: SpinalGraphUtils;
export {};
